#    This file is part of Dokkoo.
#
#    Dokkoo is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Dokkoo is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with Dokkoo.  If not, see <https://www.gnu.org/licenses/>.
[package]
name = "dokkoo"
version = "0.2.4"
authors = ["Emil Sayahi <limesayahi@gmail.com>"]
edition = "2018"
categories = ["command-line-utilities", "parser-implementations", "text-processing"]
exclude = ["/.github/**/*", "/branding/**/*", "/.gitignore", "/.whitesource", "renovate.json", "/azure-pipelines.yml", "/snapcraft.yaml"]
license = "AGPL-3.0-or-later"
description = "Mokk (Macro Output Key Kit) implementation written in Rust."
repository = "https://github.com/MadeByEmil/dokkoo"
homepage = "https://github.com/MadeByEmil/dokkoo"
readme = "README"

[lib]
name = "dokkoo"
path = "src/lib.rs"
crate-type=["rlib", "dylib", "staticlib"]

[[bin]]
name = "dokkoo"
path = "src/main.rs"
doc = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.5.0"
actix-rt = "1.1.1"
actix-web = "3.3.2"
chrono = { version = "0.4.19", features = ["unstable-locales"] }
clap = { version = "3.0.0-beta.2", features = ["yaml", "wrap_help"] }
futures = "0.3.8"
glob = "0.3.0"
lazy_static = "1.4.0"
liquid = "0.21.4"
liquid-core = "0.21.2"
liquid-lib = { version = "0.21.1", features = ["stdlib", "jekyll", "shopify", "extra"] }
notify = "4.0.15"
pathdiff = "0.2.0"
pulldown-cmark = { version = "0.8.0", default-features = false, features = ["simd"] }
serde = "1.0.118"
serde_yaml = "0.8.15"
stopwatch = "0.0.7"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
debug = 0
panic = 'abort'

[package.metadata.deb]
section = "utility"
priority = "optional"
assets = [
    ["target/x86_64-unknown-linux-gnu/release/dokkoo", "usr/bin/", "755"],
    ["target/x86_64-unknown-linux-gnu/release/libdokkoo.so", "usr/lib/", "644"],
    ["README", "usr/share/doc/dokkoo/README", "644"],
    ["COPYING", "usr/share/doc/dokkoo/COPYING", "644"],
]

[package.metadata.rpm]
package = "dokkoo"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
dokkoo = { path = "/usr/bin/dokkoo" }
