[package]
name = "dokkoo"
version = "0.1.0"
authors = ["Emil Sayahi <em@emsa.cf>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"
clap = { version = "3.0.0-beta.2", features = ["yaml", "wrap_help"] }
liquid = "*"
serde = "*"
serde_yaml = "*"

[profile.release]
codegen-units = 1
lto = true
panic = 'abort'