[package]
name = "dokkoo"
version = "0.1.0"
authors = ["Emil Sayahi <em@emsa.cf>"]
edition = "2018"
license = "AGPL-3.0-or-later"
description = "Dokkoo is a Mokk (Macro Output Key Kit) implementation written in Rust."
repository = "https://github.com/MadeByEmil/dokkoo"
readme = "README"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"
clap = { version = "3.0.0-beta.2", features = ["yaml", "wrap_help"] }
liquid = "*"
serde = "*"
serde_yaml = "*"

[profile.release]
codegen-units = 1
lto = true
panic = 'abort'

[package.metadata.deb]
section = "utility"
priority = "optional"
assets = [
    ["target/x86_64-unknown-linux-gnu/release/dokkoo", "usr/bin/", "755"],
    ["README", "usr/share/doc/dokkoo/README", "644"],
    ["COPYING", "usr/share/doc/dokkoo/COPYING", "644"],
]