#    This file is part of Dokkoo.
#
#    Dokkoo is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Dokkoo is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with Dokkoo.  If not, see <https://www.gnu.org/licenses/>.
[package]
name = "dokkoo"
version = "0.1.0"
authors = ["Emil Sayahi <limesayahi@gmail.com>"]
edition = "2018"
categories = ["command-line-utilities", "parser-implementations", "text-processing"]
exclude = ["/.github/**/*", "/branding/**/*", "/.gitignore", "/.whitesource", "/azure-pipelines.yml"]
license = "AGPL-3.0-or-later"
description = "Mokk (Macro Output Key Kit) implementation written in Rust."
repository = "https://github.com/MadeByEmil/dokkoo"
readme = "README"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "*", features = ["unstable-locales"] }
clap = { version = "3.0.0-beta.2", features = ["yaml", "wrap_help"] }
glob = "*"
liquid = "*"
liquid-core = "*"
liquid-lib = { version = "*", features = ["stdlib", "jekyll", "shopify", "extra"] }
pathdiff = "*"
pulldown-cmark = { version = "*", default-features = false, features = ["simd"] }
serde = "*"
serde_yaml = "*"
stopwatch = "*"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
debug = 0
panic = 'abort'

[package.metadata.deb]
section = "utility"
priority = "optional"
assets = [
    ["target/x86_64-unknown-linux-gnu/release/dokkoo", "usr/local/bin/", "755"],
    ["README", "usr/share/doc/dokkoo/README", "644"],
    ["COPYING", "usr/share/doc/dokkoo/COPYING", "644"],
]