# Generated by rust2rpm 25
%bcond_without check

# prevent library files from being installed
%global __cargo_is_lib() 0

%global crate dokkoo

Name:           dokkoo
Version:        0.5.0
Release:        %autorelease
Summary:        Mokk (Macro Output Key Kit) implementation written in Rust

SourceLicense:  AGPL-3.0-or-later
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/Dirout/dokkoo
Source:         # FIXME

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Mokk (Macro Output Key Kit) implementation written in Rust.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
# FIXME: install shared library

%if %{with check}
%check
%cargo_test
%endif

%files
%license COPYING
%license LICENSE.md
%license NOTICE
%license LICENSE.dependencies
%doc CODE_OF_CONDUCT.md
%doc CONTRIBUTING.md
%doc README
%doc SECURITY.md
%{_bindir}/dokkoo

%changelog
%autochangelog
