name: dokkoo
title: Dokkoo
version: git
summary: Mokk (Macro Output Key Kit) implementation written in Rust.
description: |
  Dokkoo is a Mokk (Macro Output Key Kit) implementation written in Rust.
license: AGPL-3.0
icon: branding/icon.png

base: core20
grade: stable
confinement: strict

parts:
  dokkoo:
    plugin: rust
    source: .

apps:
  dokkoo:
    command: bin/dokkoo
    plugs:
          - home
          - network
          - network-bind