on: [push]

name: 'Build: GNU + Linux (ARMv7)'

jobs:
  linux_arm7:
    name: GNU + Linux (ARMv7)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: armv7-unknown-linux-gnueabihf
          override: true
          components: rust-src
      - name: Build Dokkoo
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: -Z build-std --release --all-features --target armv7-unknown-linux-gnueabihf
      - name: Prepare Dokkoo build artifact for upload
        run: |
          strip -v --strip-all target/release/dokkoo
          chmod +x target/release/dokkoo
          tar -cvf armv7-dokkoo.gnu+linux.tar target/release/dokkoo
      - name: Upload Dokkoo build artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: armv7-dokkoo.gnu+linux
          path: armv7-dokkoo.gnu+linux.tar