on: [push]

name: 'Package: AUR Binary (x86_64)'

jobs:
  aur_x86-64:
    name: Arch Linux (x86_64)
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      volumes:
        - /proc:/proc
        - /sys/fs/cgroup/systemd/actions_job:/sys/fs/cgroup/systemd/actions_job
        - /sys/fs/cgroup:/sys/fs/cgroup
      options: --privileged
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Install compiler toolchain
        run: |
          pacman -Syu gcc git openssh base-devel --noconfirm
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          override: true
          components: rust-src
      - name: Install 'cargo-aur'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-aur
      - name: Generate AUR binary package
        uses: actions-rs/cargo@v1
        with:
          command: aur
      - name: Push to AUR
        run: |
          mkdir ./aur
          cd ./aur
          git clone ssh://aur@aur.archlinux.org/dokkoo-bin.git
          cp -avf ../dokkoo-*-x86_64.tar.gz
          cp -avf ../PKGBUILD
          makepkg --printsrcinfo > .SRCINFO
          git config user.name "emsa"
          git config user.email "limesayahi@gmail.com"
          git add -A
          git commit -m "Automatically updating Dokkoo release via GitHub Actions"
          git push