on: [push]

name: 'Package: Debian GNU + Linux (x86_64)'

jobs:
  deb_x86-64:
    name: Debian GNU + Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          override: true
          components: rust-src
      - name: Install 'cargo-deb'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb
      - name: Prepare building & packaging environment
        run: |
          mkdir -p ./target/x86_64-unknown-linux-gnu/release
          ln -s ./target/x86_64-unknown-linux-gnu/release ./target/release
      - name: Build & package Dokkoo
        uses: actions-rs/cargo@v1
        with:
          command: deb
          args: --separate-debug-symbols -- --all-features --target x86_64-unknown-linux-gnu
      - name: Upload Dokkoo build artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-dokkoo.deb.gnu+linux
          path: ./target/debian/dokkoo_*_amd64.deb