name: Publish documentation to GitHub Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Publish documentation"
    steps:
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-unknown-linux-gnu
        default: true
        profile: default
    - name: Checkout codebase
      uses: actions/checkout@v2
      with:
          path: ./dokkoo
    - name: Generate documentation
      uses: actions-rs/cargo@v1
      with:
        command: doc
    - name: Checkout GitHub Pages environment
      uses: actions/checkout@v2
      with:
          ref: gh-pages
          path: ./gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Move generated documentation to GitHub Pages environment
      run: |
          sudo apt-get -qq install tree > /dev/null
          printf "Files to build:\n" && tree ./mokk
          find ./gh-pages -mindepth 1 ! -regex '^./gh-pages/.git\(/.*\)?' -delete
          cp -ar ./dokkoo/doc/* ./gh-pages
          touch ./gh-pages/.nojekyll
          tee -a ./gh-pages/.nojekyll > /dev/null <<EOT

          EOT
          printf "\nFiles to publish:\n" && tree ./gh-pages
    - name: Publish
      run: |
          cd ./gh-pages
          git config --global user.name 'Dokkoo'
          git config --global user.email 'MadeByEmil@users.noreply.github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -am "Publish documentation to GitHub Pages"
          git push
