on: [push]

name: 'Build: macOS (ARM64)'

jobs:
  mac_aarch64:
    name: macOS (ARM64)
    runs-on: macos-11
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-apple-darwin
          default: true
          profile: minimal
      - name: Build Dokkoo
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target aarch64-apple-darwin
      - name: Prepare Dokkoo for upload
        run: |
          cd ./target/aarch64-apple-darwin/release/
          strip ./dokkoo
          chmod +x ./dokkoo
          tar -cvf aarch64-dokkoo.osx.tar \
          dokkoo \
          libdokkoo.dylib \
          libdokkoo.a
      - name: Upload Dokkoo build artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: aarch64-dokkoo.osx
          path: ./target/aarch64-apple-darwin/release/aarch64-dokkoo.osx.tar
          if-no-files-found: error
