on: [push]

name: 'Build: macOS (x86_64)'

jobs:
  mac_x86-64:
    name: macOS (x86_64)
    runs-on: macos-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-darwin
          override: true
          components: rust-src
      - name: Build Dokkoo
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target x86_64-apple-darwin
      - name: Prepare Dokkoo for upload
        run: |
          cd ./target/x86_64-apple-darwin/release/
          strip ./dokkoo
          chmod +x ./dokkoo
          tar -cvf x86_64-dokkoo.osx.tar \
          dokkoo \
          libdokkoo.dylib \
          libdokkoo.a
      - name: Upload Dokkoo build artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-dokkoo.osx
          path: x86_64-dokkoo.osx.tar
          if-no-files-found: error