on: [push]

name: 'Build: macOS (x86_64)'

jobs:
  linux_arm7:
    name: macOS (x86_64)
    runs-on: macos-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-darwin
          override: true
          components: rust-src
      - name: Build Dokkoo
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target x86_64-apple-darwin
      - name: Prepare Dokkoo build artifact for upload
        run: |
          strip ./target/x86_64-apple-darwin/release/dokkoo
          chmod +x ./target/x86_64-apple-darwin/release/dokkoo
          tar -cvf x86_64-dokkoo.osx.tar ./target/x86_64-apple-darwin/release/dokkoo
      - name: Upload Dokkoo build artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-dokkoo.osx
          path: x86_64-dokkoo.osx.tar