on: [push]

name: 'Build: Windows (x86_64)'

jobs:
  linux_arm7:
    name: Windows (x86_64)
    runs-on: windows-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-pc-windows-msvc
          override: true
          components: rust-src
      - name: Build Dokkoo
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target x86_64-pc-windows-msvc
      - name: Upload Dokkoo build artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-dokkoo.win32
          path: ./target/release/dokkoo