on: [push]

name: 'Build: GNU + Linux (x86_64)'

jobs:
  linux_x86-64:
    name: GNU + Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          override: true
          components: rust-src
      - name: Build Dokkoo
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target x86_64-unknown-linux-gnu
      - name: Prepare Dokkoo build artifact for upload
        run: |
          strip -v --strip-all ./target/x86_64-unknown-linux-gnu/release/dokkoo
          chmod +x ./target/x86_64-unknown-linux-gnu/release/dokkoo
          tar -cvf x86_64-dokkoo.gnu+linux.tar ./target/x86_64-unknown-linux-gnu/release/dokkoo
      - name: Upload Dokkoo build artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-dokkoo.gnu+linux
          path: x86_64-dokkoo.gnu+linux.tar
          if-no-files-found: error