on: [push]

name: 'Build: GNU + Linux (x86_64)'

jobs:
  linux_x86-64:
    name: GNU + Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          default: true
          profile: minimal
      - name: Build Dokkoo
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target x86_64-unknown-linux-gnu
      - name: Prepare Dokkoo for upload
        run: |
          cd ./target/x86_64-unknown-linux-gnu/release/
          strip -v --strip-all ./dokkoo
          strip -v --strip-all ./libdokkoo.so
          strip -v --strip-all ./libdokkoo.a
          chmod +x ./dokkoo
          tar -cvf x86_64-dokkoo.gnu+linux.tar \
          dokkoo \
          libdokkoo.so \
          libdokkoo.a
      - name: Upload Dokkoo build artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-dokkoo.gnu+linux
          path: ./target/x86_64-unknown-linux-gnu/release/x86_64-dokkoo.gnu+linux.tar
          if-no-files-found: error